# frps.toml
bindPort = 7894 # 服务端与客户端通信端口

auth.token = "public" # 身份验证令牌，frpc要与frps一致

# Server Dashboard，可以查看frp服务状态以及统计信息
webServer.addr = "0.0.0.0" # 后台管理地址
webServer.port = 7540 # 后台管理端口
webServer.user = "admin"
webServer.password = "admin"
